nodeLinker: node-modules
enableGlobalCache: true
nmHoistingLimits: none
nmMode: hardlinks-local
pnpFallbackMode: none
supportedArchitectures:
  os: [current]
  cpu: [current]

npmRegistryServer: "https://registry.npmjs.org/"

npmScopes:
  pagerduty:
    npmAlwaysAuth: true
    npmAuthToken: NPM_TOKEN

yarnPath: .yarn/releases/yarn-4.4.1.cjs
