nodeLinker: node-modules
enableGlobalCache: true
nmHoistingLimits: none
nmMode: hardlinks-local
pnpFallbackMode: none
supportedArchitectures:
  os: [current]
  cpu: [current]

yarnPath: .yarn/releases/yarn-4.4.1.cjs
