compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

npmRegistries:
  "https://pagerduty-staging.spotifyportal.com/api/plugin-installer/registry/npm":
    npmAuthToken: g7kXFEpdfYJsSDhBPxT6O/XDyZlrYJrr

yarnPath: .yarn/releases/yarn-4.4.1.cjs