enableGlobalCache: true

nmHoistingLimits: none

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

npmScopes:
  pagerduty:
    npmAlwaysAuth: true
    npmAuthToken: NPM_TOKEN

plugins:
  - checksum: a7960e90b20fe64de29d899d907dd9d539f4111357d84ce89eab20c01ea2941d4d4ee2a569d220be2f92f93d63cee18b85a6273cbb74980564fb80f7ee7c64d2
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: "https://versions.backstage.io/v1/releases/1.45.3/yarn-plugin"

pnpFallbackMode: none

supportedArchitectures:
  cpu:
    - current
  os:
    - current

yarnPath: .yarn/releases/yarn-4.4.1.cjs
