name: Release

on:
  workflow_dispatch:
    inputs:
      pre-release:
        description: 'Is this a pre-release version?'
        required: true
        default: true
        type: boolean

jobs:
  # Publish all packages with independent versioning using changesets
  publish_to_npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Need full history for changesets
          fetch-depth: 0
      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
      - name: Install yarn
        run: corepack enable
      - name: Set yarn version to latest stable
        run: corepack prepare yarn@stable --activate
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn lint:all
      - name: Test
        run: yarn test:all
      - name: Build
        run: yarn build
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have created changeset files for any changes you want to release
          # Run `yarn changeset` locally to create these files
          publish: yarn release
          title: 'Release new versions'
          commit: 'Release new versions'
          setupGitUser: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.npm_token }}
      - name: Publish pre-release versions
        if: ${{ inputs.pre-release && steps.changesets.outputs.published != 'true' }}
        run: |
          yarn changeset version --snapshot beta
          yarn changeset publish --tag beta
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}
